### ISSUE TITLE
[BUG] Error 500 when finish signing a document

### ISSUE THREAD

**Issue by lukasver** [documenso/documenso#626]
### Issue Description

Trying out the `app.documenso.com` app, created a test pdf document and sent it to 2 signers. When last signer of a document tries to confirm the signature, an error 500 is thrown in an HTTP call and submit button is stuck in infinite loading state.
When going to dashboard, the document appears as signed but an email is never sent to document issuer to notify all parties have signed.

### Steps to Reproduce

1) Create a document to sign in `app.documenso.com`.
2) Send it to at least 2 recipients.
3) Sign document as first recipient.
4) Try to sign as second recipient and see error happening.

### Expected Behavior

- Error shoul be gracefully handled in frontend with some UI indicator and infinity loader should not happen.
- Document sender should be notified if status is changed to completed.

### Screenshots (optional)

![image](https://github.com/documenso/documenso/assets/63676303/1b97509f-73c7-4b78-bc64-b309d06c8a7e)

### Operating System [e.g., Windows 10]

MacOS Sonoma14

### Browser [e.g., Chrome, Firefox]

Chrome

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, I remember this PDF it has security settings on it that mean it can't be updated or modified. I'll try and find the thread where I last worked with this but if you open the given test document in Adobe Reader you'll see the permission flags that have been set 😄

**Comment by Mythie** [comment]
Can't find the thread anymore but if you see the flags set here you'll notice that modifications are disabled:
<img width="913" alt="image" src="https://github.com/documenso/documenso/assets/13398220/c451658b-3b9f-4d8f-8bd5-77c220f14455">

We are working on adding functionality to catch these kinds of documents and display an appropriate error or remove the restrictions.

**Comment by poorna-prakash-sr** [comment]
I can work on it

**Comment by lukasver** [comment]
> Hey there, I remember this PDF it has security settings on it that mean it can't be updated or modified. I'll try and find the thread where I last worked with this but if you open the given test document in Adobe Reader you'll see the permission flags that have been set 😄

Woah! was not aware of this at all! thanks for clarifying!. i'll try again with a different pdf

**Comment by Mythie** [comment]
I'm keeping this open so we can work towards improving the experience when dealing with documents with these protections enabled.

But I will be locking the thread for now until we return to this 🙌🏻

**Comment by dguyen** [comment]
Should be resolved now since we do a precheck to see if a document can be edited when it's initially uploaded.
